name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main
env:
  # for easingthemes/ssh-deploy
  SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
  REMOTE_HOST: ${{ secrets.EC2_HOST }}
  REMOTE_USER: ${{ secrets.EC2_USER }}
  TARGET: ${{ secrets.EC2_OUTPUT_DIR }}
  SOURCE: '../WebScraper'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.1
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.1'
        architecture: 'x64'
    # - name: Get Python version
    #   run: python -V
    # - name: Install dependencies
    #   run: pip install -r requirements.txt
    - name: Generate GoogleAccessTokenFile
      run: echo ${{ secrets.GOOGLE_ACCESS_TOKEN }}>./app/MercariPriceMonitor/google_token_file.json
    - name: Generate configuretion file
      run: python ./app/MercariPriceMonitor/gen_config.py --line_token ${{ secrets.LINE_ACCESS_TOKEN }} --google_token_file ./app/MercariPriceMonitor/google_token_file.json --google_workbook ${{ secrets.GOOGLE_WORKBOOK_KEY }}
    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v2.1.1
